### ISSUE TITLE
How do I pass values to the HTML interface, using loadData or postUrl, and how should the HTML interface accept parameters?

### ISSUE THREAD

**Issue by wangyn111** [pichillilorenzo/flutter_inappbrowser#102]

**Comment by wangyn111** [comment]
![image](https://user-images.githubusercontent.com/24839576/58403886-5faaf580-8096-11e9-979f-c55d842383d0.png)
I found a solution to ban'f in an example.

**Comment by dharmitaepaisa** [comment]
@wangyn111 On what event you have called this method?

**Comment by pr0ph0z** [comment]
@wangyn111 thank you for the example syntax, I can't pass the `postData` as `null`. Yet, you have to at least send the empty string as @wangyn111 provide above.

@dharmitaepaisa It might very late but you can call this method in onWebViewCreated event.

Hope this will help future users.
