### ISSUE TITLE
HttpOnly Cookies

### ISSUE THREAD

**Issue by TsunaDev** [pichillilorenzo/flutter_inappbrowser#11]
Hey,
I was wondering if there was a way to get the HttpOnly cookies or is it possible to share the session with a http request ?

**Comment by pichillilorenzo** [comment]
Unfortunately, there is no way to get HttpOnly cookies. In case, you can set cookies that will be used by the WebView using the `CookieManager.setCookie` method. For example:
```dart
await CookieManager.setCookie("https://flutter.io/", "myCookieName", "myCookieValue");
```

**Comment by TsunaDev** [comment]
The fact is that I need to get a token (that's stored as a HttpOnly cookie) on the WebView and use it to request some info on the server.
So the only way is to get the HttpOnly cookie or to be able to share cookies between the WebView and my Http requests but it seems not possible.

**Comment by pichillilorenzo** [comment]
The problem is that WebViews don't give access to HttpOnly cookies.
So, maybe you can try using the dart [HttpClient](https://api.dartlang.org/stable/2.0.0/dart-io/HttpClient-class.html) class to get your HttpOnly cookie:
```dart
import 'dart:io';
import 'dart:async';

Future main() async {
  String token;

  HttpClient client = new HttpClient();

  client.getUrl(Uri.parse("<HERE_MY_URL>")) // or client.postUrl
    .then((HttpClientRequest request) {
      // Optionally set up headers...
      // Optionally write to the request object...
      // Then call close.
      return request.close();
    })
    .then((HttpClientResponse response) {
      // Process the response.
      List<Cookie> cookies = response.cookies;
      print(cookies);
      // Loop the cookies to search your specific cookie with the token 
      for (var cookie in cookies) {
        if (cookie.name == "<MY_COOKIE_NAME>") {
          token = cookie.value;
          print(token);
          break;
        }
      }
    });
}
```
In this way you can get your token and then you can use it for your next requests.

Let me know if it works.
