### ISSUE TITLE
Android fails with Error: uses-sdk:minSdkVersion 16 cannot be smaller than version 17 declared in library [:flutter_inappbrowser]

### ISSUE THREAD

**Issue by alsocalledchris** [pichillilorenzo/flutter_inappbrowser#14]
After adding the plugin to my project (using Flutter 0.11.3) Android builds fail with:

AndroidManifest.xml Error: uses-sdk:minSdkVersion 16 cannot be smaller than version 17 declared in library [:flutter_inappbrowser] ...

.. as the library might be using APIs not available in 16
	Suggestion: use a compatible library with a minSdk of at most 16,
		or increase this project's minSdk version to at least 17,
		or use tools:overrideLibrary="com.pichillilorenzo.flutter_inappbrowser" to force usage (may lead to runtime failures)

**Comment by pichillilorenzo** [comment]
The `minSdkVersion` is already setted to at least 17! Just see the [build.gradle](https://github.com/pichillilorenzo/flutter_inappbrowser/blob/master/android/build.gradle) file.

**Comment by alsocalledchris** [comment]
@pichillilorenzo many thanks for your quick reply - I'm sure it is, however that was the error I got when adding the package and then trying to run it in my Android VM running Pie - I didn't do anything else and I haven't made any manual changes to the Android build files etc. Any ideas on how to fix this? Many thanks (super keen to get this plugin working as looks like it does exactly what we need 👍)

**Comment by alsocalledchris** [comment]
Oh hang on - I need to update my AndroidManifest file don't I - so that has the higher version as requested by this plugin? Let me check...

**Comment by alsocalledchris** [comment]
Yep, sorry - that was the problem. Thanks. Any chance the iOS build issue as a similar easy issue?

**Comment by velsa** [comment]
@alsocalledchris 
I am not very experienced with Android development yet.
Could you please explain what needs to be changed in AndroidManifest to set the higher version of the sdk library?

Thanks

**Comment by dchaofei** [comment]
@velsa try change file `android/app/build.gradle` minSdkVersion config

sorry! I can not speak English

**Comment by Charan-Sajjanapu** [comment]
> 
> 
> Oh hang on - I need to update my AndroidManifest file don't I - so that has the higher version as requested by this plugin? Let me check...

Can you please elaborate what you did?

**Comment by gc986** [comment]
Hi! The library description says that minSdk = 17, but the library manifest specifies 20. What is the current minimum version of the Sdk for the library?
