### ISSUE TITLE
iOS fails with SWIFT_VERSION build setting must be set even after running flutter create -i swift

### ISSUE THREAD

**Issue by alsocalledchris** [pichillilorenzo/flutter_inappbrowser#15]
Can't build the iOS app after adding this package to my project. Fails with SWIFT_VERSION error even though I have run the 'flutter create -i swift' command on the directory the project is in.

The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. Supported values are: 3.0, 4.0, 4.2. This setting can be set in the build settings editor.

Using Flutter 0.11.3 with latest XCode.

**Comment by ChiefRed** [comment]
Hi! I have here: Flutter 0.11.3 and XCode 10.1 (10B61) 

Just have tried to create new project with -i swift and run code from InAppBrowser example:  https://github.com/pichillilorenzo/flutter_inappbrowser#inappbrowser-class

And it's compiling! But fails at run browser - just killing app.

Then I'v removed all extra code from example:

```
import 'package:flutter/material.dart';
import 'package:flutter_inappbrowser/flutter_inappbrowser.dart';

class MyInAppBrowser extends InAppBrowser {}

MyInAppBrowser inAppBrowser = new MyInAppBrowser();

void main() => runApp(new MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => new _MyAppState();
}

class _MyAppState extends State<MyApp> {

  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      home: new Scaffold(
        appBar: new AppBar(
          title: const Text('Flutter InAppBrowser Plugin example app'),
        ),
        body: new Center(
          child: new RaisedButton(onPressed: () async {
            await inAppBrowser.open(url: "https://flutter.io/", options: {
            });
          },
              child: Text("Open InAppBrowser")
          ),
        ),
      ),
    );
  }
}
```

Now it's running. And for Android too.

But my main project crying about tons of errors... Looks like I need recreate it from zero.

**Comment by pichillilorenzo** [comment]
`flutter create -i swift` is used when you create a new fresh app and not for updating one.
@ChiefRed @alsocalledchris can you post here logs/screenshots of the errors you get? Thanks!

**Comment by ChiefRed** [comment]
@pichillilorenzo, I have recreated my main project. Now it's working.
IMHO, SWIFT_VERSION error may be just unstable environment result. Then flutter clear & relaunch IDE may help.

**Comment by chuongtrh** [comment]
Try to edit Pod file. More clear at [here](https://stackoverflow.com/questions/50458556/flutter-swift-version-must-be-set-to-a-supported-value)

```
target 'Runner' do
  use_frameworks!  # required by simple_permission
  ...
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '4.0'  # required by simple_permission
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
```

**Comment by ChenArno** [comment]
Me too, my xcode version is also 10.1

**Comment by Winner28** [comment]
Same problem

**Comment by Ger123** [comment]
getting this error 

`flutter_inappbrowser` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.
`

**Comment by Sagi363** [comment]
Same problem

**Comment by pichillilorenzo** [comment]
@ChenArno @Winner28 @Sagi363 did you try the solution of @chuongtrh?

> Try to edit Pod file. More clear at [here](https://stackoverflow.com/questions/50458556/flutter-swift-version-must-be-set-to-a-supported-value)
> 
> ```
> target 'Runner' do
>   use_frameworks!  # required by simple_permission
>   ...
> end
> 
> post_install do |installer|
>   installer.pods_project.targets.each do |target|
>     target.build_configurations.each do |config|
>       config.build_settings['SWIFT_VERSION'] = '4.0'  # required by simple_permission
>       config.build_settings['ENABLE_BITCODE'] = 'NO'
>     end
>   end
> end
> ```

**Comment by Sagi363** [comment]
> @ChenArno @Winner28 @Sagi363 did you try the solution of @chuongtrh?
> 
> > Try to edit Pod file. More clear at [here](https://stackoverflow.com/questions/50458556/flutter-swift-version-must-be-set-to-a-supported-value)
> > ```
> > target 'Runner' do
> >   use_frameworks!  # required by simple_permission
> >   ...
> > end
> > 
> > post_install do |installer|
> >   installer.pods_project.targets.each do |target|
> >     target.build_configurations.each do |config|
> >       config.build_settings['SWIFT_VERSION'] = '4.0'  # required by simple_permission
> >       config.build_settings['ENABLE_BITCODE'] = 'NO'
> >     end
> >   end
> > end
> > ```

It worked finally, Thank you very much!

**Comment by pichillilorenzo** [comment]
Ok! I will add this solution in the README.md file!

**Comment by alsocalledchris** [comment]
The above solution works for me - thanks everyone!

**Comment by franzejr** [comment]
I think this solution only works if you have Swift as a default language, no @pichillilorenzo @alsocalledchris ?

**Comment by horgag1** [comment]
What worked for me was the above and then I 

  changed the configuration in "ios/Runner.xcodeproj/project.pbxproj":
from
VERSIONING_SYSTEM = "apple-generic";
to

SWIFT_SWIFT3_OBJC_INFERENCE=On;
SWIFT_VERSION=4.0;


There are 3 instances
