### ISSUE TITLE
ERR_CLEARTEXT_NOT_PERMITTED in android 9

### ISSUE THREAD

**Issue by emidiao** [pichillilorenzo/flutter_inappbrowser#158]
hi, I'm receiving this error in android 9 when launching an instance of InAppLocalhostServer and browsing a http://localhost:8080 page with InAppBrowser
I already tried the solutions suggested here https://developer.android.com/training/articles/security-config#CleartextTrafficPermitted
or here https://stackoverflow.com/a/50834600 (tried with "localhost" or "127.0.0.1" but it doesnt work. Do you have any suggestions?
thanks

**Comment by kuhnroyal** [comment]
What was your solution to this?

**Comment by ishaan-puniani** [comment]
looking for the same solution
