### ISSUE TITLE
swift complier error (swift 5.0 support)

### ISSUE THREAD

**Issue by fattiger00** [pichillilorenzo/flutter_inappbrowser#160]
My project today extension widget was written by swift 5, so I had to support swift 5 . when I run the project, I got bunches of the compiler error.

**Comment by gaojuanjuan** [comment]
I also have this problem.
error：
![image](https://user-images.githubusercontent.com/14133759/65398442-cb556300-dde9-11e9-94e0-de7bf815e753.png)

**Comment by fattiger00** [comment]
> I also have this problem.
> error：
> ![image](https://user-images.githubusercontent.com/14133759/65398442-cb556300-dde9-11e9-94e0-de7bf815e753.png)

I had sent a pull request ( #162 ) .you can do it manually, open it with xcode ,and

**Comment by fattiger00** [comment]
> I also have this problem.
> error：
> ![image](https://user-images.githubusercontent.com/14133759/65398442-cb556300-dde9-11e9-94e0-de7bf815e753.png)

I had sent a pull request #162 . or you can do it manually. 

1.open the project with Xcode
2.click menu **Edit** -> **Convert** -> **To Current Swift Syntax…**
3.select **flutter_inappbrowser** to and click next.
4.it will had errors. replace `self.tmpWindow?.windowLevel = UIWindowLevel(baseWindowLevel!+ 1)`
to`self.tmpWindow?.windowLevel = UIWindow.Level(baseWindowLevel!.rawValue + 1)`

then working fine
