### ISSUE TITLE
Target platform ios is not yet supported by the flutter_inappbrower plugin

### ISSUE THREAD

**Issue by chuongtrh** [pichillilorenzo/flutter_inappbrowser#18]
I tried to create new project with -i swift  but facing a issue 

> Target platform ios is not yet supported by the flutter_inappbrower plugin

How to fix it? Thanks

[Image of issue](https://imgur.com/a/wTYzo8W)

**Comment by pichillilorenzo** [comment]
Like said in the README.md file, `InAppWebView` is only available for Android at this moment!

**Comment by chuongtrh** [comment]
Hope, release soon on iOS :)

**Comment by pichillilorenzo** [comment]
Yeah! I'm working on it 😄

**Comment by MarcelEdward** [comment]
+1 I hope the webview will function on ios soon

**Comment by Ger123** [comment]
same question as above!

**Comment by pichillilorenzo** [comment]
I think I'm going to publish the next version these days!

**Comment by winsonet** [comment]
oh, I am waiting for your new version, thanks!!!!

**Comment by DreamBuddy** [comment]
Thanks deeply,i'm waiting for the new version,too!

**Comment by pichillilorenzo** [comment]
Sorry guys, I know but these days I'm really busy due to my last Master's degree project exam! I think next week I could continue to work on this plugin! 👍. Sorry again!

**Comment by juliengit2** [comment]
We are also impatiently waiting for the ios version, thank you deeply too!

**Comment by pichillilorenzo** [comment]
I'm happy to announce that I finally released the new version **0.6.0** with support for **iOS inline native WebView** integrated into the flutter widget tree! 😄  Let me know about any problems you will have.
