### ISSUE TITLE
How to open to new schema?

### ISSUE THREAD

**Issue by tankchuen** [pichillilorenzo/flutter_inappbrowser#188]
I use addthis plugin inside webview, when click share to social media will hit net:ERR_UNKNOWN_URL_SCHEME

i'm add these to my code still not working
```
initialOptions: {
     'resourceCustomSchemes': ["fb-messenger","tg","whatsapp"]
}
```

Is any where can fixed this? Thank you

![WhatsApp Image 2019-11-09 at 1 45 13 PM](https://user-images.githubusercontent.com/24307098/68523676-3950dd80-02f7-11ea-9054-3a6f91903347.jpeg)

**Comment by pichillilorenzo** [comment]
`resourceCustomSchemes` option is used by the `onLoadResourceCustomScheme` event to intercept resource requests with custom scheme. For example in your html you have something like this: 
```html
 <img src="my-special-custom-scheme://images/flutter-logo.svg" alt="flutter logo">
```
So, in the `initialOptions` you would have:
```dart
initialOptions: InAppWebViewWidgetOptions(
    inAppWebViewOptions: InAppWebViewOptions(
        resourceCustomSchemes: ["my-special-custom-scheme"],
    )
)       
```
and the event handler could be something like this:
```dart
onLoadResourceCustomScheme: (InAppWebViewController controller, String scheme, String url) async {
  if (scheme == "my-special-custom-scheme") {
    var bytes = await rootBundle.load("assets/" + url.replaceFirst("my-special-custom-scheme://", "", 0));
    var response = new CustomSchemeResponse(bytes.buffer.asUint8List(), "image/svg+xml", contentEnconding: "utf-8");
    return response;
  }
  return null;
},
```

Instead, in your case you want to handle custom schemes that are not about resources like images, etc. So, in this case, you need to set the `InAppWebViewOptions.useShouldOverrideUrlLoading` option to `true` and to use `shouldOverrideUrlLoading` event:
```dart
shouldOverrideUrlLoading: (InAppWebViewController controller, String url) {
  if (url.startsWith("whatsapp://")) {
    // Open WhatsApp app
  } else if (url.startsWith("foo://")) {
    // check for other apps ...
  }
},
```
If you want to open an app like WhatsApp, you can use my other plugin [flutter_appavailability](https://github.com/pichillilorenzo/flutter_appavailability).

However, you are using the **2.0 flutter_inappbrowser version** that is not published yet. I need to finish the new documentation and create at least some tests before publishing it. Of course, you can use it at your own risk for now.
