### ISSUE TITLE
app crashing on iOS when using ChromeSafariBrowser

### ISSUE THREAD

**Issue by marquesinijatinha** [pichillilorenzo/flutter_inappbrowser#19]
* created a new project with `flutter create -i swift webview_test`
* added `flutter_inappbrowser: 0.5.51` to pubspec.yaml
* replaced button code with
`void _incrementCounter() {
    ChromeSafariBrowser browser = new ChromeSafariBrowser(null);
    browser.open('http://flutter.io');
}`
App crashes when clicking the button.
InAppBrowser works fine.

**Comment by ignoracenfly** [comment]
has it been fixed?

**Comment by marquesinijatinha** [comment]
yep
