### ISSUE TITLE
iOS CookieManager setCookie doesn't wait for cookie to actually have been set

### ISSUE THREAD

**Issue by ollisal** [pichillilorenzo/flutter_inappbrowser#196]
Hi and thanks for the great library! Especially happy about the scroll callback which allows us to implement some nice effects in our app.

We have one problem though - we inject a particular login session used by the outside app to inside InAppWebViews using CookieManager. On Android this works perfectly. On iOS the cookies aren't available in the InAppWebView reliably when needed, especially if another InAppWebView has been alive in the app before.

I think this might be due to the iOS CookieManager not passing a `completionHandler` when it calls the `setCookie` method:

https://github.com/pichillilorenzo/flutter_inappbrowser/blob/68ff79c71686987fc5bdc447f2c68a723a821ca6/ios/Classes/MyCookieManager.swift#L96

That WKHTTPCookieStore method DOES have a completion handler, like the other methods we're calling, which we pass a completion handler to: https://developer.apple.com/documentation/webkit/wkhttpcookiestore/2882007-setcookie?language=objc

Is there some reason why the completion handler isn't used here? As a workaround, we can loop to check for the cookies having been set, but that's a bit messy.

**Comment by robertcnst** [comment]
#198 this may help you :)

**Comment by pichillilorenzo** [comment]
Updated the master branch with that fix and created the new 1.2.2 version with only that fix.

**Comment by koskimas** [comment]
Wow, that was fast! Thank you @robertcnst and @pichillilorenzo! 🍻

**Comment by ollisal** [comment]
@pichillilorenzo Thanks! We've now verified that the fixed version works without any workarounds for setting the cookies.
