### ISSUE TITLE
ChromeSafariBrowser doesn't work in Given Example

### ISSUE THREAD

**Issue by VipinMalik7** [pichillilorenzo/flutter_inappbrowser#197]
## Description
The Given Example in the ChromeSafariBrowser doesn't work. 
chromeSafariBrowser.open() should be present in the Class but it isn't present.

**Expected behavior:** 
Open a chrome Browser.
**Current behavior:** 
Doesn't Even Compile, let alone running.
## Steps to reproduce

Just Copy the Example of the ChromeSafariBrowser and paste it in a new Flutter project and add the required pubspec dependency.
Then there is no open function in the library.

**Comment by pichillilorenzo** [comment]
The current example of the master branch contains new APIs that differs from v1.2.1.
If you are using v.1.2.1, then go here https://github.com/pichillilorenzo/flutter_inappbrowser/tree/v1.2.1

If you want use the master branch (that isn't already published yet), you need to point the dependency on the master branch of this repository (see https://flutter.dev/docs/development/packages-and-plugins/using-packages#dependencies-on-unpublished-packages).
