### ISSUE TITLE
Cannot take screenshot for WebView by using RepaintBoundary?

### ISSUE THREAD

**Issue by zhaoya188** [pichillilorenzo/flutter_inappbrowser#25]
[screenshot](https://github.com/zhaoya188/FlutterBlurDemo/raw/master/webview-screen.png)
<div align=center><img width="400" height="700" src="https://github.com/zhaoya188/res/raw/master/img/webview-screen.png"/></div>

**Comment by pichillilorenzo** [comment]
I think the problem is that because `InAppWebView` uses the native widget of the platform, so `RepaintBoundary` won't work here. However, to take a screenshot of the `InAppWebView` page, you can use the `inAppWebViewController.takeScreenshot()` method!

**Comment by datpt11** [comment]
takeScreenshot not only captures the content in the viewport, but not all webview content @pichillilorenzo
