### ISSUE TITLE
 java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference E/MethodChannel#com.pichillilorenzo/flutter_inappbrowser( 9990)

### ISSUE THREAD

**Issue by krsolutions** [pichillilorenzo/flutter_inappbrowser#32]
E/MethodChannel#com.pichillilorenzo/flutter_inappbrowser( 9990): Failed to handle method call
E/MethodChannel#com.pichillilorenzo/flutter_inappbrowser( 9990): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
E/MethodChannel#com.pichillilorenzo/flutter_inappbrowser( 9990): 	at com.pichillilorenzo.flutter_inappbrowser.InAppBrowserFlutterPlugin.onMethodCall(InAppBrowserFlutterPlugin.java:100)
E/MethodChannel#com.pichillilorenzo/flutter_inappbrowser( 9990): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:200)
E/MethodChannel#com.pichillilorenzo/flutter_inappbrowser( 9990): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
E/MethodChannel#com.pichillilorenzo/flutter_inappbrowser( 9990): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#com.pichillilorenzo/flutter_inappbrowser( 9990): 	at android.os.MessageQueue.next(MessageQueue.java:323)
E/MethodChannel#com.pichillilorenzo/flutter_inappbrowser( 9990): 	at android.os.Looper.loop(Looper.java:136)
E/MethodChannel#com.pichillilorenzo/flutter_inappbrowser( 9990): 	at android.app.ActivityThread.main(ActivityThread.java:6123)
E/MethodChannel#com.pichillilorenzo/flutter_inappbrowser( 9990): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#com.pichillilorenzo/flutter_inappbrowser( 9990): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
E/MethodChannel#com.pichillilorenzo/flutter_inappbrowser( 9990): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
E/flutter ( 9990): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter ( 9990): PlatformException(error, Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference, null)
E/flutter ( 9990): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:551:7)
E/flutter ( 9990): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:292:18)
E/flutter ( 9990): <asynchronous suspension>
E/flutter ( 9990): #2      ChromeSafariBrowser.open (package:flutter_inappbrowser/flutter_inappbrowser.dart:491:35)
E/flutter ( 9990): <asynchronous suspension>
E/flutter ( 9990): #3      _HomeScreenState.build.<anonymous closure> (package:leader/home/view/home_screen.dart:129:42)
E/flutter ( 9990): <asynchronous suspension>
E/flutter ( 9990): #4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:507:14)
E/flutter ( 9990): #5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:562:30)
E/flutter ( 9990): #6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
E/flutter ( 9990): #7      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:242:9)
E/flutter ( 9990): #8      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:175:7)
E/flutter ( 9990): #9      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:315:9)
E/flutter ( 9990): #10     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
E/flutter ( 9990): #11     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
E/flutter ( 9990): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:180:19)
E/flutter ( 9990): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:158:22)
E/flutter ( 9990): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:138:7)
E/flutter ( 9990): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:101:7)
E/flutter ( 9990): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:85:7)
E/flutter ( 9990): #17     _invoke1 (dart:ui/hooks.dart:168:13)
E/flutter ( 9990): #18     _dispatchPointerDataPacket (dart:ui/hooks.dart:122:5)

**Comment by pichillilorenzo** [comment]
Should be fixed with the new version **0.6.0**!
