### ISSUE TITLE
ChromeSafariBrowser.open Exception

### ISSUE THREAD

**Issue by laurent-humbert** [pichillilorenzo/flutter_inappbrowser#33]
Hi,

I wanted to use your plugin but it seems that version 0.5.51 on dartlang.org is a bit behind compared to the Github version and doesn’t include a missing 

args.putIfAbsent('isData', () => false);

in ChromeSafariBrowser.open

This causes an exception.

Any chance you could make a 0.5.52 ?

Thanks;

Laurent

**Comment by HotPepperDaddy** [comment]
I had the same problem.  In case you didn't know, you can do this in pubspec.yaml:

  flutter_inappbrowser:
    git: https://github.com/pichillilorenzo/flutter_inappbrowser.git

**Comment by pichillilorenzo** [comment]
Should be fixed with the new version **0.6.0**!
