### ISSUE TITLE
can't load HTML file in assets folder

### ISSUE THREAD

**Issue by Nanank-kho** [pichillilorenzo/flutter_inappbrowser#39]
Hii,,

Any example code to load HTML file in assets folder ?

thanks

**Comment by alsocalledchris** [comment]
This worked fine for me @Nanank-kho - make sure you add your asset via the pubspec.yaml file e.g:

assets:
    - assets/index.html
    - assets/css/
    - assets/images/

See https://github.com/pichillilorenzo/flutter_inappbrowser/tree/master/example

I can get it displaying the index HTML file correctly.

**Comment by shahxadakram** [comment]
I am facing the same issue..

**Comment by shahxadakram** [comment]
I was facing the same issue, there was a problem in indentation of assets.
It must be like this
  assets:
    - assets/index.html
    - assets/css/
    - assets/images/
