### ISSUE TITLE
InAppWebView iOS

### ISSUE THREAD

**Issue by zakaryus** [pichillilorenzo/flutter_inappbrowser#45]
In the readme, it is mentioned that InAppWebView is currently only supported for Android, and you were waiting on the Flutter team before you could add iOS

> InAppWebView: Flutter Widget for adding an inline native WebView integrated in the flutter widget tree. [Available only for Android (AndroidView) at this moment. For iOS, it will be available as soon as the Flutter team will release the corresponding dart class.].

I came across [UiKitView](https://docs.flutter.io/flutter/widgets/UiKitView-class.html) today, and I was curious if that was the equivalent iOS class you were waiting on?

If so, I would greatly appreciate it if you would be able to get iOS support added for the InAppWebView. 

Thanks for the great library!

**Comment by sageata** [comment]
I desperately need that as well 👍

**Comment by pichillilorenzo** [comment]
Yeah guys, I know but these days I'm really busy due to my last Master's degree project exam! I think next week I could continue to work on this plugin! 👍. Sorry again!

**Comment by sageata** [comment]
Good luck with completing your Master degree...

**Comment by juliengit2** [comment]
we also desperately need that, impatient to see it compatible on ios, I'm almost checking everyday if there is any evolution

**Comment by pichillilorenzo** [comment]
I'm happy to announce that I finally released the new version **0.6.0** with support for **iOS inline native WebView** integrated into the flutter widget tree! 😄  Let me know about any problems you will have.

**Comment by MarcelEdward** [comment]
Thank for the update.

Got it to run, but got this error:

[VERBOSE-2:platform_view_layer.cc(19)] Trying to embed a platform view but the PrerollContext does not support embedding
[VERBOSE-2:platform_view_layer.cc(28)] Trying to embed a platform view but the PaintContext does not support embedding

After adding this to /ios/Runner/Info.plist it works:

    <key>io.flutter.embedded_views_preview</key>
    <true/>
