### ISSUE TITLE
Do you think it's possible to catch console output?

### ISSUE THREAD

**Issue by flddr** [pichillilorenzo/flutter_inappbrowser#5]
Thanks for your work.

I would like to test this, but, the question in title is also interesting to me :)

**Comment by pichillilorenzo** [comment]
Yeah I think it is possible!

For Android it is very simple: I need to add the [onConsoleMessage](https://developer.android.com/reference/android/webkit/WebChromeClient#onConsoleMessage(android.webkit.ConsoleMessage)) method.

For iOS I think I can use something like:
[https://stackoverflow.com/a/33751939/4637638](https://stackoverflow.com/a/33751939/4637638)
[https://stackoverflow.com/a/49148633/4637638](https://stackoverflow.com/a/49148633/4637638)

**Comment by flddr** [comment]
That sounds great for me :) what do you think about timing? This year, ore morely unknown?

Thanks for fast response :+1:

**Comment by pichillilorenzo** [comment]
@flddr released **new version 0.2.1**! Now you can use and overidde the `onConsoleMessage` method to listen console messages coming from the webview.

Quick example:
```dart
class MyInAppBrowser extends InAppBrowser {

  @override
  Future onLoadStop(String url) async {
    // console messages
    await this.injectScriptCode("console.log({'testObject': 5});"); // the message will be: [object Object]
    await this.injectScriptCode("console.log('testObjectStringify', JSON.stringify({'testObject': 5}));"); // the message will be: testObjectStringify {"testObject": 5}
    await this.injectScriptCode("console.error('testError', false);"); // the message will be: testError false
  }

  @override
  void onConsoleMessage(ConsoleMessage consoleMessage) {
    print("""
    console output:
      sourceURL: ${consoleMessage.sourceURL}
      lineNumber: ${consoleMessage.lineNumber}
      message: ${consoleMessage.message}
      messageLevel: ${consoleMessage.messageLevel}
    """);
  }

}
```

You can find the example in the README.md file 😄

**Comment by flddr** [comment]
Wow! Unbelievable :100:

Thank you very much :hugs:

**Comment by flddr** [comment]
Can i ask you another question? I am figuring out if it is possible in flutter to build a dev tool with control over complete request structure and i want to get raw response as `string` or `byte[]` before it`s consumed by dart parser. Do you have an idea; maybe, in combination with your plugin? :)

**Comment by pichillilorenzo** [comment]
@flddr I think that something could be done

**Comment by flddr** [comment]
@pichillilorenzo i tried to get some info here https://github.com/dart-lang/http/issues/207 but actually not... I am newbie to dart, so just looking if it could be a good idea...

What do you think?

Thank you :)

**Comment by pichillilorenzo** [comment]
So you need to use the Socket class! In this way I think you could manage raw requests/responses! See this example: [https://stackoverflow.com/questions/51077233/how-can-i-use-socket-in-flutter-app](https://stackoverflow.com/questions/51077233/how-can-i-use-socket-in-flutter-app)
