### ISSUE TITLE
iOS onLoadResource no longer works for requested local resources

### ISSUE THREAD

**Issue by alsocalledchris** [pichillilorenzo/flutter_inappbrowser#58]
onLoadResource method for InAppBrowser is not hit if the resource being requested is local (e.g. http://localhost being hosted by InAppLocalhostServer) this worked in 0.5.51.

**Comment by alsocalledchris** [comment]
shouldOverrideUrlLoading is not hit at all anymore on iOS

**Comment by alsocalledchris** [comment]
onLoadResource is not called if the resource is local either (external requests work fine)

**Comment by pichillilorenzo** [comment]
I'm not able to reproduce your problem! 

Are you sure that you have set to true the needed options?
```json
{
    "useShouldOverrideUrlLoading": true,
    "useOnLoadResource": true
}
```

Otherwise, can you give me the code that is not working? For example you can create a repository with the sample code that is not working! Thanks

**Comment by alsocalledchris** [comment]
Tested again and it was due to a server side redirect (302) that was not being picked up with shouldOverrideUrlLoading. Using onLoadStop which catches it instead.

**Comment by pichillilorenzo** [comment]
Ok, I need to investigate more on this! Thanks
