### ISSUE TITLE
Cannot start 

### ISSUE THREAD

**Issue by berialcheng** [pichillilorenzo/flutter_inappbrowser#6]
Version: 4

Target:
iPhone XS Max simulator

Console:
=== BUILD TARGET flutter_inappbrowser OF PROJECT Pods WITH CONFIGURATION Debug ===
The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. Supported values are: 3.0, 4.0, 4.2. This setting can be set in the build settings editor.

**Comment by pichillilorenzo** [comment]
See #4 ! You need to create the flutter app with `flutter create -i swift`

**Comment by berialcheng** [comment]
Thanks  , that would be nice if README.md had these.
 
I went through most of the webview plugins. found it most interesting and extensible,  appreciate your work , hoping it would be better.

**Comment by pichillilorenzo** [comment]
Yeah I'm going to add it in the next commit!

Thanks, I'm working a lot on it and I'm adding new features every time!
I will add also the possibility of inline webviews using AndroidView and the same implementation for iOS when they will be available / stable enough.
