### ISSUE TITLE
Some problem with javascriptHanlder

### ISSUE THREAD

**Issue by yhdjy025** [pichillilorenzo/flutter_inappbrowser#64]
My window.flutter_inappbrowser object have a method named _callHandler but not callHandler
and I call this method, _callHandler in my JS code, but the InAppWebViewController can not recive the call

My js code:
```javascript
  console.log('----------------------_callHandler--------------')
            console.log(window.flutter_inappbrowser._callHandler)
            console.log('----------------------callHandler--------------')
            console.log(window.flutter_inappbrowser.callHandler)
            //call app
            try {
                window.flutter_inappbrowser._callHandler('message', 'hello');
            } catch (e) {
                console.log(e)
            }
```

My dart code
```dart
return InAppWebView(
      initialUrl: Constant.SERVER_ADDRESS +
          'extendmng/zz/userIndex?apptype=2&userid=' +
          userInfo.userid +
          '&token=' +
          userInfo.token +
          '&os=' +
          (defaultTargetPlatform == TargetPlatform.android ? 'android' : 'ios'),
      initialHeaders: {},
      initialOptions: {'safeBrowsingEnabled': false},
      onWebViewCreated: (InAppWebViewController controller) {},
      onLoadStart: (InAppWebViewController controller, String url) {
        controller.addJavaScriptHandler('message', (params) {
          print(params.toString());
        });
      },
      onProgressChanged: (InAppWebViewController controller, int progress) {
        print('----------------' + progress.toString());
      },
      onConsoleMessage:
          (InAppWebViewController controller, ConsoleMessage consoleMessage) {
        print(consoleMessage.message);
      },
    );
```

see th picture
![企业微信截图_15525518426364](https://user-images.githubusercontent.com/11054900/54341777-aa12fd80-4675-11e9-981a-72453cd4a60d.png)

**Comment by pichillilorenzo** [comment]
Yeah I know! I fixed this problem in the last commit :+1: .. I need to update the documentation because there is a little change on how it works! Later I'm going to publish the new version

**Comment by pichillilorenzo** [comment]
Feature added now on the new version **1.1.0**. 
Inside an html file, you may want use this:
```html
<script>
        // you need to wait and listen the JavaScript event flutterInAppBrowserPlatformReady
        window.addEventListener("flutterInAppBrowserPlatformReady", function(event) {
            console.log("ready");
            // then you can call the window.flutter_inappbrowser.callHandler() method.
            // callHandler() returns a Promise that you can use to get data from Dart side.
            window.flutter_inappbrowser.callHandler('handlerFoo').then(function(result) {
                console.log(result, typeof result);
                console.log(JSON.stringify(result), result.bar);
            });

            window.flutter_inappbrowser.callHandler('handlerFooWithArgs', 1, true, ['bar', 5], {foo: 'baz'}).then(function(result) {
                console.log(result, typeof result);
                console.log(JSON.stringify(result));
            });
        });
</script>
```
Instead, on the `onLoadStop` Dart event, you can use `callHandler` directly:
```dart
// Inject JavaScript that will receive data back from Flutter
webView.injectScriptCode("""
  window.flutter_inappbrowser.callHandler('test', 'Text from Javascript').then(function(result) {
    console.log(result);
  });
""");
```

**Comment by yhdjy025** [comment]
I have tested in some diff version SDK android emulator,I find some devices do not have callHandler function in window.flutter_inappbrowser object,.so I  guess there has compatible problem on it.

**Comment by pichillilorenzo** [comment]
Which version?? Thanks

**Comment by yhdjy025** [comment]
I use the Genmotion created Nexus 5 - API23 of Android emulator.
look at the picture

![企业微信截图_15528980511553](https://user-images.githubusercontent.com/11054900/54517108-c37cb800-499b-11e9-948c-aba467c9dbb1.png)

![企业微信截图_15528981233731](https://user-images.githubusercontent.com/11054900/54517149-dbecd280-499b-11e9-997c-ca6e1f6c7491.png)

And it continuous print W/art    ' ( 1866): Attempt to remove non-JNI local reference, dumping thread='

**Comment by yhdjy025** [comment]
I find the _callHandler function is exist,
Means the object add by addJavascriptInterface function is success, and add by evaluateJavascript is failed

**Comment by pichillilorenzo** [comment]
Ok! I will try that!

**Comment by yhdjy025** [comment]
I've found the reason. look at the screenshot
![企业微信截图_15529656761553](https://user-images.githubusercontent.com/11054900/54578090-633c5380-4a39-11e9-8264-5ce0f1bbab6b.png)

because the ...args is support in ES6, some android simulator's browser core do not support it.
