### ISSUE TITLE
AllowsInlineMediaPlayback not working!

### ISSUE THREAD

**Issue by docaohuynh** [pichillilorenzo/flutter_inappbrowser#73]
Hi team!
I want Display youtube video inline on IOS devices but It's always fullscreen when play
I have some code like this
```
InAppWebView(
            initialUrl: "https://youtube.com/...",
            initialHeaders: {

            },
            initialOptions: {
              "allowsInlineMediaPlayback": true,
            }
...
);
```
**video tag generate**
`<video tabindex="-1" class="video-stream html5-main-video" webkit-playsinline="" playsinline="" controlslist="nodownload" style="width: 366px; height: 206px; left: 323.389px; top: 0px;" src="blob:https://www.youtube.com/af98e547-89b5-4594-b54d-9325fe046597"></video>`

**Comment by ShiroYacha** [comment]
seconding this... it doesn't seem to work with Vimeo either

**Comment by ShiroYacha** [comment]
To test this use https://developers.google.com/youtube/youtube_player_demo as the `initialUrl` and set the option `playsinline` and update the player. The player will still play as full screen on iOS devices.
