### ISSUE TITLE
InAppBrowser crashes the app when i change the page "Lost connection" 

### ISSUE THREAD

**Issue by shubhamnatani** [pichillilorenzo/flutter_inappbrowser#74]
When i run the Flutter app and go to the inappbrowser and then get back to the my origin page.
it crashes the app in ios mode not in android.
Please responded fast as soon as possible.

InAppWebView(
                    initialUrl: 'www.google.com',
                    onWebViewCreated: (InAppWebViewController controller) {
                      webView = controller;
                    },

                    onProgressChanged: (InAppWebViewController controller, int progress) {
                      setState(() {
                        this.progress = progress/100;
                      });
                    },
                    
                    gestureRecognizers: Set()
                      ..add(Factory<VerticalDragGestureRecognizer>(
                              () => VerticalDragGestureRecognizer())),
                  ),

**Comment by pichillilorenzo** [comment]
Can you post here the logs please?

**Comment by shubhamnatani** [comment]
one line is generated.
Lost connection to device when i shift from inappbrowser to my vertical page.

**Comment by shubhamnatani** [comment]
Can you please repsond it fast.I am stuck just because of this issue.

**Comment by ashbressler** [comment]
I believe that I'm experiencing the same issue. I'm getting the following error in the XCode log:

`2019-04-08 15:42:55.196097-0400 Runner[40818:798573] Fatal error: Unexpectedly found nil while unwrapping an Optional value`

and in the Stack it looks like it's happening here:

https://github.com/pichillilorenzo/flutter_inappbrowser/blob/master/ios/Classes/InAppWebView.swift#L797

It looks like it's trying to invokeMethod 'onConsoleMessage'

I have attached screenshots of what I think are the debug stack at the time of the crash. If you would like more detail that u can't see in the screens please let me know.

![Screen Shot 2019-04-08 at 3 58 45 PM](https://user-images.githubusercontent.com/102587/55753031-5f3b9a00-5a17-11e9-834b-9e91ca0bcacd.png)

![Screen Shot 2019-04-08 at 3 58 54 PM](https://user-images.githubusercontent.com/102587/55753067-77abb480-5a17-11e9-80c1-06f416a15723.png)

![Screen Shot 2019-04-08 at 3 58 59 PM](https://user-images.githubusercontent.com/102587/55753099-84c8a380-5a17-11e9-87b7-07555dda7450.png)

**Comment by vigupta7** [comment]
Hey pichillilorenzo,  Please check and confirm the way to resolve this issue, as there is not webview widget in flutter that gives the onProgressChange event..

Also, If pagechange triggers this issue, I was thinking of a way to dispose the webview at 90% of page change.. please suggest, if there is any function to dispose the webview.

**Comment by vigupta7** [comment]
Friends, Any Update on the issue ?

**Comment by vigupta7** [comment]
pichillilorenzo, please update on the rectification. this is a serious issue and we are not able to use this plugin.

**Comment by pichillilorenzo** [comment]
Yes! Sorry guys! I will update it as soon as possible!!

**Comment by Gentear** [comment]
@pichillilorenzo   Friends,  When will it be updated?

**Comment by pichillilorenzo** [comment]
Plugin updated! Try the new version `1.1.2` and let me know if now it works! Thanks

**Comment by vigupta7** [comment]
Awesome and Thanks !!
Its working fine now.
