### ISSUE TITLE
Compatibility with other plugins

### ISSUE THREAD

**Issue by alexelisenko** [pichillilorenzo/flutter_inappbrowser#80]
I am using the flutter_inappbrowser plugin in my project, as well as audioservice.

If I open a browser view before ever starting the audio service, all is okay, but if I start the audio service, then open the browser, the app crashes with the error:

```
08:54:03.581 145 info flutter.tools E/AndroidRuntime(31364): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
```

The call stack stops around here:

```
08:54:03.583 148 info flutter.tools E/AndroidRuntime(31364): 	at com.pichillilorenzo.flutter_inappbrowser.InAppBrowserActivity.show(InAppBrowserActivity.java:309)
08:54:03.583 149 info flutter.tools E/AndroidRuntime(31364): 	at com.pichillilorenzo.flutter_inappbrowser.InAppBrowserActivity.prepareView(InAppBrowserActivity.java:98)
08:54:03.583 150 info flutter.tools E/AndroidRuntime(31364): 	at com.pichillilorenzo.flutter_inappbrowser.InAppBrowserActivity.onCreate(InAppBrowserActivity.java:69)
```

I suspect this could be related to audioservice requiring a custom MainApplication class, but I don't have much Android development experience, so any insight/help would be much appreciated.

audioservice plugin: https://github.com/ryanheise/audio_service

**Comment by pichillilorenzo** [comment]
This should be fixed with the new version **1.2.0**
