### ISSUE TITLE
Keyboard is not showing

### ISSUE THREAD

**Issue by chunkeat96** [pichillilorenzo/flutter_inappbrowser#9]
Inline webview
When i focus on text field, the keyboard is not showing. Anybody can help with this issue? Thanks a lot!
![capture](https://user-images.githubusercontent.com/44486757/47541526-2053d500-d90c-11e8-8985-b7fa258b1072.PNG)

**Comment by pichillilorenzo** [comment]
As you can already see in the README.md file at the top of InAppWebView class section:

AndroidView is not officially stable yet! So, if you want use it, you can but you will have some limitation such as the inability to use the keyboard!

**Comment by chunkeat96** [comment]
okay. Thanks for replying.

**Comment by pichillilorenzo** [comment]
Unfortunately I can't do anything about that 😞.. We need to wait that the Flutter team will release a stable version of it.. The same is for the iOS.
