### ISSUE TITLE
where run the app,something wrong

### ISSUE THREAD

**Issue by soar20** [pichillilorenzo/flutter_inappbrowser#92]
uses-sdk:minSdkVersion 16 cannot be smaller than version 17 declared in library [:flutter_inappbrowser] G:\flutterApp\demo01\build\flutter_inappbrowser\intermediates\merged_manifests\debug\processDebugManifest\merged\AndroidManifest.xml as the library might be using APIs not available in 16
	Suggestion: use a compatible library with a minSdk of at most 16,
		or increase this project's minSdk version to at least 17,
		or use tools:overrideLibrary="com.pichillilorenzo.flutter_inappbrowser" to force usage (may lead to runtime failures)
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 17 declared in library [:flutter_inappbrowser] G:\flutterApp\demo01\build\flutter_inappbrowser\intermediates\merged_manifests\debug\processDebugManifest\merged\AndroidManifest.xml as the library might be using APIs not available in 16

**Comment by pichillilorenzo** [comment]
As already mentioned in the README.md of the repository (https://github.com/pichillilorenzo/flutter_inappbrowser#note-for-android), you need to update the `minSdkVersion` of your `build.gradle` file to at least `17`.
